### ISSUE TITLE
[Crash]: Server crashing randomly when users load new chunks or teleport using waystones/RTP

### ISSUE THREAD

**Issue by Lightveld** [AllTheMods/ATM-10#1251]
### Possible Fixes

Yes

### Modpack Version

1.24

### What happened?

A specific user is crashing the server constantly when moving around to load new chunks or using waystones or RTP

### Crash Log

https://gist.github.com/Lightveld/0ca41098d755d10fc97dd1ba20c61ffa

### Latest.Log

https://gist.github.com/Lightveld/4fe08f7472cfe1d66631a70781c69630

**Comment by thesekcy** [comment]
the same thing happens to me in singleplayer

**Comment by Slothfulsins** [comment]
Can confirm, not sure if it's happening in the TF but since we updated to 1.24, we're seeing random crashes from exploration. Presumably in the overworld. TF has a ton of issues.

**Comment by mymusicmanager** [comment]
Can confirm!
Still getting the issue, as late as today.
Minecraft crashes after a few moment trying to load the new chunks.
Would like to see a fix for this, Waystones is a really neat QoL mod that makes the world so much more accessable.

**Comment by alekthefirst** [comment]
Likely issue with Ars Noveau particles unloading, fixed in Ars Noveau 5.2.3 released with ATM10 1.17

**Comment by mymusicmanager** [comment]
Nope, still crashes for me. Updated the pack with today's update 2.9.
Minecraft crashes when using Waystones, returning exit code -1 with the reason `The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{minecraft:void_air}`.

Complete crash log can be found here: https://pastebin.com/rQAcuube

**Comment by alekthefirst** [comment]
> Nope, still crashes for me. Updated the pack with today's update 2.9. Minecraft crashes when using Waystones, returning exit code -1 with the reason `The game crashed whilst ticking block entity Error: java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{minecraft:void_air}`.
> 
> Complete crash log can be found here: https://pastebin.com/rQAcuube

This is a very different crash that will get fixed in restrictions 7.0.3
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1214
Will be included in the ATM release coming after the 7.0.3 release of restrictions, until then, recommend not using the mod
