### ISSUE TITLE
[Bug]: Kubejs/MysticalAgriculture/Fusioncrafting server script errors

### ISSUE THREAD

**Issue by BIGFAAT** [AllTheMods/ATM-10#1286]
### Possible Fixes

Yes

### Modpack Version

1.25

### What happened?

Greetings, seems 2 recipes are for now broken in 1.25:
![Screenshot_20241129_182702](https://github.com/user-attachments/assets/e211a3e5-b0a1-421a-b0ee-5dc75ec6d8c4)
Thanks in advance!

### latest.log

https://gist.github.com/BIGFAAT/72116bb8463bd974f35ce452ff339232

**Comment by eodrambo** [comment]
several more are broken in 1.26, I'm seeing 32 of them now.

**Comment by eodrambo** [comment]
I didn't get to post my logs, but the issue seems to be corrected with V 2.1

**Comment by TheBedrockMaster** [comment]
Let me know if you still get this on version 2.1

**Comment by BIGFAAT** [comment]
> Let me know if you still get this on version 2.1

Issue is still existing. I replace the Kubejs folder at every update. Maybe do I miss something?
![Screenshot_20241216_085311](https://github.com/user-attachments/assets/35e049dd-61d9-4687-bce5-a715fbadb89d)

**Comment by BIGFAAT** [comment]
I reinstalled the server and the issue is gone for now.
