### ISSUE TITLE
[Bug]: 'no matching output bus found' error message in runic star altar controller...

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#1418]
### Possible Fixes

Yes

### Modpack Version

10.2.5

### What happened?

made the runic star altar, took some effort.  I have tried item output blocks in all the possible slots, the multi block forms but it doesn't recognise the output to run..?  is there a specific tier of output block or a specific position for it to be in? I only want to output a single item so id think I only need the tiny item output?  think im ready to go otherwise but I just need this item output to recognise.

**Comment by alekthefirst** [comment]
Team has worked with MMR dev and issue should be resolved in ATM10 2.6. Runic Star Altar now able to craft stars again as it was on 2.3
![image](https://github.com/user-attachments/assets/842ea923-d99d-4336-af41-f3fc260e1e21)

**Comment by DaddyLongspoon** [comment]
thanks so much alek1, you're clearly a champion.

**Comment by DaddyLongspoon** [comment]
update. 10.2.6 did indeed fix my star altar.  but it broke my auto heph forge :( now that one tells me 'no fluid input hatch found' .  it has four of the biggest ones, was working in 10.2.25..? getting there guys.  thanks, I love your packs and appreciate your efforts.

**Comment by shade1822226911** [comment]
> update. 10.2.6 did indeed fix my star altar. but it broke my auto heph forge :( now that one tells me 'no fluid input hatch found' . it has four of the biggest ones, was working in 10.2.25..? getting there guys. thanks, I love your packs and appreciate your efforts.

same here, just a tip: you can pull out of the input hatches using the mek pipes, might help in breaking and replacing

**Comment by DaddyLongspoon** [comment]
reloading the overworld, returning from some other dimension seems to trigger this bug afresh, a multi block that was working happily acquires the 'no hatch of type x found' bug..  the crucuble (or whatever its called, the one that makes fluid aural and fluid soul juice) lost one of its hatches today, first time< when I returned from twilight forest.. (yes the chunk is loaded so it could be something else..). the star altar had it as well.. on the crucible and star altar breaking and replacing a hatch fixes things, not so the auto heph forge sadly, that hasn't worked for me at any time in 10.26

**Comment by shade1822226911** [comment]
> reloading the overworld, returning from some other dimension seems to trigger this bug afresh, a multi block that was working happily acquires the 'no hatch of type x found' bug.. the crucuble (or whatever its called, the one that makes fluid aural and fluid soul juice) lost one of its hatches today, first time< when I returned from twilight forest.. (yes the chunk is loaded so it could be something else..). the star altar had it as well.. on the crucible and star altar breaking and replacing a hatch fixes things, not so the auto heph forge sadly, that hasn't worked for me at any time in 10.26

Considering this isn't a bug that only happens to one person, I'm gonna make a bug report for this

**Comment by alekthefirst** [comment]
Fixed in dev on MMRs end, see https://github.com/alec016/modular-machinery-reborn/issues/21

**Comment by PiggyWhiskey** [comment]
Issue is still occurring.

![image](https://github.com/user-attachments/assets/f944f40c-fd34-41a2-b774-ff22544faef8)
![image](https://github.com/user-attachments/assets/85f89db5-1067-4c6e-9389-13bb359951bc)

ATM10 v2.13

**Comment by Beffa90** [comment]
I also have the same issue with the Hephaestus Forge, which is placed in the Mining Dim. Is says "No fluid input hatch found" and I've tried to break and replace as well as upgrading all hatches to maximum tier with no luck. I'm also on ATM10 v2.13.
