### ISSUE TITLE
[Bug]: Ender Storage pouch missing in JEI

### ISSUE THREAD

**Issue by Ustabil2** [AllTheMods/ATM-10#2136]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-2.32

### What happened?

seem like the Ender Pouch from ender storage is not visible in JEI but the recipe can be found when looking up usage for ender perls

![Image](https://github.com/user-attachments/assets/542caec8-8963-491c-908b-f2db48bb0beb)

**Comment by pietro-lopes** [comment]
Can reproduce, will report to devs.
![Image](https://github.com/user-attachments/assets/171848b7-391d-4d56-8d17-11ee64180a6d)

**Comment by covers1624** [comment]
This has been fixed in CCL build: https://maven.covers1624.net/io/codechicken/CodeChickenLib/1.21.1-4.6.0.521/CodeChickenLib-1.21.1-4.6.0.521.jar

Should be available on Curse/Modrinth shortly.

**Comment by Ustabil2** [comment]
still missing in All the Mods 10-2.33

![Image](https://github.com/user-attachments/assets/7837a9a0-2e67-4c26-aeca-89157617fccf)
